import { normalizeLandingSection, type LandingSectionContent } from "./landingContent";

export type AboutSectionContent = LandingSectionContent;

export const defaultAboutSections: AboutSectionContent[] = [
  {
    key: "about-hero",
    name: "About Hero",
    enabled: true,
    eyebrow: "About Moksha Sewa",
    title: "Serving the Final Journey With Dignity",
    subtitle: "A humanitarian initiative of Namo Gange Trust.",
    description: "Moksha Sewa stands beside families, authorised unclaimed cases and people without support with care, responsibility and compassion.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164944/moksha-sewa/hero-images/dignity-in-every-final-journey-bg.png",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164952/moksha-sewa/hero-images/image6.png",
    buttonLabel: "Request Sewa Help",
    buttonHref: "/request-help",
    secondaryButtonLabel: "Support This Mission",
    secondaryButtonHref: "/donation",
    quote: "We do not see a case. We see a human life that deserves respect.",
    items: [
      { title: "For Those Unclaimed", description: "Dignified rites for unclaimed." },
      { title: "For Those Alone", description: "Support for the alone." },
      { title: "For Families in Need", description: "Help for families in need." },
      { title: "With Dignity & Care", description: "Compassion in every farewell." },
      { title: "Humanity First", description: "Every life is precious and deserves respect." },
      { title: "Verification & Legal", description: "We follow formalities and check eligibility first." },
      { title: "Transparent Sewa", description: "Accountable and compassionate at every step." },
      { title: "Community Powered", description: "Powered by volunteers, supporters and partners." },
    ],
  },
  {
    key: "about-who-we-are",
    name: "Who We Are",
    enabled: true,
    eyebrow: "Who We Are",
    title: "Moksha Sewa Is a Namo Gange Trust Initiative.",
    description: "Moksha Sewa is a dedicated humanitarian initiative of Namo Gange Trust, created to provide compassionate and responsible support for authorised unclaimed cases, people without family support, and verified families facing financial hardship.",
    secondaryDescription: "The initiative operates under the guidance and institutional framework of Namo Gange Trust, bringing together volunteers, coordinators, service partners and compassionate citizens to support dignified final journeys.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165070/moksha-sewa/assets/about-reference/who-we-are-background-v2.png",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165236/moksha-sewa/assets/logo-moksha-seva.png",
    supportTitle: "MOKSHA SEWA",
    supportDescription: "A Namo Gange Trust Initiative",
    bottomStatement: "Together, we ensure that no one is left without dignity, care and respect in their final journey.",
    items: [
      { title: "Compassion", description: "At Every Step" },
      { title: "Integrity", description: "In Every Action" },
      { title: "Respect", description: "For Every Life" },
      { title: "Dignity", description: "In Every Journey" },
    ],
  },
  {
    key: "about-moksha-sewa",
    name: "What Is Moksha Sewa",
    enabled: true,
    eyebrow: "What Is Moksha Sewa?",
    title: "A Mission Built\nAround Dignity.",
    description: "Moksha Sewa is a humanitarian initiative created to stand beside people during one of life's most difficult and sensitive moments - the final journey.",
    secondaryDescription: "It focuses on authorised unclaimed cases, people without available family support, and verified families who may face financial hardship in arranging essential final-journey requirements.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164982/moksha-sewa/assets/about-optimized/a_mission.png",
  },
  {
    key: "about-services",
    name: "What We Do",
    enabled: true,
    eyebrow: "What We Do",
    title: "Supporting the\nFinal Journey With Care.",
    description: "We provide compassionate and responsible support for every step of the final journey.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165007/moksha-sewa/assets/about-optimized/moksha_services_bg.png",
    buttonLabel: "Explore Our Sewa",
    buttonHref: "/prayerhallservices",
    secondaryTitle: "How We Serve",
    items: [
      { title: "Final-Journey\nTransport", description: "Dignified and timely transport to the cremation destination.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165003/moksha-sewa/assets/about-optimized/final_journey_support.png" },
      { title: "Cremation &\nLast-Rites Support", description: "Complete support for cremation and essential last-rites arrangements.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164997/moksha-sewa/assets/about-optimized/cremation.png" },
      { title: "Ritual & Priest\nCoordination", description: "Arranging priests and guidance for all required rituals with respect.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165017/moksha-sewa/assets/about-optimized/ritual.png" },
      { title: "Essential\nMaterials", description: "Providing all essential items required for the final rites.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164998/moksha-sewa/assets/about-optimized/essentials.png" },
      { title: "Family\nGuidance", description: "Emotional support and guidance for families during difficult times.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165002/moksha-sewa/assets/about-optimized/family_guidance.png" },
      { value: "01", title: "Understand", description: "We listen to the circumstances.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165024/moksha-sewa/assets/about-optimized/understand.png" },
      { value: "02", title: "Verify", description: "Eligibility and required formalities are reviewed.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165025/moksha-sewa/assets/about-optimized/verify.png" },
      { value: "03", title: "Coordinate", description: "Essential support is arranged as applicable.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164995/moksha-sewa/assets/about-optimized/coordinate.png" },
      { value: "04", title: "Stand Beside", description: "Compassionate on-ground guidance continues through the process.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165021/moksha-sewa/assets/about-optimized/stand_behind.png" },
    ],
  },
  {
    key: "about-how-support",
    name: "Who We Support",
    enabled: true,
    title: "Who We Support",
    legalNotice: "Important Note",
    bottomStatement: "Support is case-based and subject to applicable verification, eligibility, required formalities and available resources.",
    items: [
      { value: "01", title: "Unclaimed &\nAuthorised Cases", description: "Support for authorised cases after applicable procedures, permissions and formalities.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165060/moksha-sewa/assets/about-reference/story-ghat-temple.png" },
      { value: "02", title: "People Without\nFamily Support", description: "Compassionate assistance for people who have no family or support system available to stand beside them.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165059/moksha-sewa/assets/about-reference/story-evening-ghat.png" },
      { value: "03", title: "Verified Families Facing\nFinancial Hardship", description: "Case-based assistance for families who need help with essential final-rites arrangements.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165001/moksha-sewa/assets/about-optimized/family-support.webp" },
    ],
  },
  {
    key: "about-why-exist",
    name: "Why We Exist",
    enabled: true,
    eyebrow: "Why We Exist",
    title: "Because Sometimes,\nThere Is No One Left\nto Stand Beside Them.",
    subtitle: "Moksha Sewa\nExists for These Moments.",
    description: "Some people leave this world without family or support.\nSome cases remain unclaimed. And some families have the love and willingness to perform the final rites, but do not have the financial means to manage everything on their own.",
    quote: "When support disappears,\nhumanity must step forward.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165000/moksha-sewa/assets/about-optimized/existimage.png",
  },
  {
    key: "about-behind-mission",
    name: "Mission Video",
    enabled: true,
    eyebrow: "Video",
    title: "Behind\nMoksha Sewa",
    subtitle: "See the Mission",
    description: "Every final journey carries a story. This is the story of a mission built around responsibility, compassion and the belief that no one should be left without dignity.",
    image: "/vedio/taniya.mp4",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164962/moksha-sewa/hero-images/support-mission-ghat.png",
    availabilityText: "60-90 seconds",
    buttonLabel: "Explore Our Work",
    buttonHref: "/mokshagallery",
    items: [
      { title: "WHAT", label: "We Do" },
      { title: "WHY", label: "We Exist" },
      { title: "WHO", label: "We Serve" },
      { title: "HOW", label: "We Serve" },
      { title: "NAMO GANGE TRUST", label: "Our Foundation" },
    ],
  },
  {
    key: "about-our-story",
    name: "Our Story & Founder Message",
    enabled: true,
    eyebrow: "Our Story",
    title: "One Question\nBecame a Mission.",
    subtitle: "What happens when someone passes away\nand there is no one to stand beside them?",
    description: "This question became the foundation of Moksha Sewa—a mission created so that when someone is left without family, support or resources, humanity can still stand beside them.\n\nWe believe that every individual, regardless of identity, status or circumstance, deserves a final journey of dignity, respect and compassion.",
    quote: "Dignity should never depend on whether someone has money, family or someone standing beside them.",
    secondaryTitle: "A Message From The Founder",
    secondaryDescription: "Moksha Sewa is not just a service—it is a promise. A promise that in someone's final moment, humanity will not look away.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165477/moksha-sewa/assets/vijay_sharma.jpg",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164976/moksha-sewa/assets/about/our-story/ghat-background.png",
  },
  {
    key: "about-namo-gange",
    name: "Namo Gange Trust",
    enabled: true,
    eyebrow: "The Organisation Behind Moksha Sewa",
    title: "Rooted in Service.\nDriven by Responsibility.",
    description: "Moksha Sewa is an initiative of Namo Gange Trust, an organisation committed to social service, community welfare and meaningful humanitarian action.",
    secondaryDescription: "Through Moksha Sewa, Namo Gange Trust extends this commitment to one of the most sensitive moments of human life - the final journey.",
    image: "/assets/videos/namoGange.mp4",
    buttonLabel: "Know Namo Gange Trust",
    buttonHref: "https://www.namogange.org/",
    items: [
      { label: "Social Service" },
      { label: "Community Welfare" },
      { label: "Humanitarian Action" },
      { label: "Responsible Governance" },
    ],
  },
  {
    key: "about-responsible-sewa",
    name: "Responsible Sewa",
    enabled: true,
    eyebrow: "Responsible Sewa",
    title: "Compassion\nWith Accountability.",
    subtitle: "We serve with responsibility. Because dignity comes first.",
    description: "At Moksha Sewa, every act of support is guided by responsibility, respect and the highest standards of ethical service.\n\nWe ensure that no one is left behind, working with deep empathy to provide dignity when it is needed most.",
    bottomStatement: "Moksha Sewa is a Namo Gange Trust initiative. Every step we take is guided by responsibility, respect and humanity.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164979/moksha-sewa/assets/about/our-story/response.jpg",
    items: [
      { title: "Verification", description: "Support follows defined eligibility and case circumstances." },
      { title: "Formalities", description: "Applicable permissions and procedures are respected." },
      { title: "Documentation", description: "Cases and assistance are responsibly recorded." },
      { title: "Privacy", description: "Beneficiary dignity comes before publicity." },
    ],
  },
  {
    key: "about-support-mission",
    name: "Support The Mission",
    enabled: true,
    eyebrow: "Support The Mission",
    title: "Help Namo Gange Trust\nContinue Moksha Sewa.",
    description: "Moksha Sewa is a humanitarian initiative of Namo Gange Trust. Your contribution helps support the Trust's efforts to provide dignified and responsible final-journey assistance through the Moksha Sewa initiative.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164974/moksha-sewa/assets/about/our-story/arthi.jpg",
    legalNotice: "Contributions made through this website are received by Namo Gange Trust and are utilised towards eligible activities and support under the Moksha Sewa initiative, subject to applicable policies and requirements.",
    items: [
      { title: "Essential final-journey arrangements" },
      { title: "Transportation & coordination" },
      { title: "Ritual requirements" },
      { title: "Eligible family support" },
      { title: "On-ground coordination" },
      { title: "Secure & Trusted", description: "Safe donations through trusted gateway" },
      { title: "Accountable Use", description: "Funds used for eligible activities only" },
      { title: "Transparency First", description: "Committed to responsible reporting" },
      { title: "Sewa With Dignity", description: "Ensuring respect and compassion in every step of the final journey" },
    ],
  },
  {
    key: "about-join-sewa",
    name: "Be Part Of The Sewa",
    enabled: true,
    eyebrow: "BE PART OF THE SEWA",
    title: "You Don't Have to\nDo Everything.",
    subtitle: "You Can Simply Do Something.",
    description: "Every act of kindness creates a ripple of dignity, compassion and respect. Even a small contribution of time, care or support can bring comfort to someone during their most difficult moments and help ensure that no one has to face their final journey alone.\n\nWhether you give your time as a volunteer, partner with us as an organisation, or support a family directly, every contribution helps us stand beside those who need it most — with dignity, care and respect.",
    bottomStatement: "Together, we can make sure that no one has to face their final journey alone. Be Part of the Sewa. Be the change.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164993/moksha-sewa/assets/about-optimized/be_part.png",
    items: [
      { title: "Become a Volunteer", description: "Give your time.\nBring compassion.\nBe the reason someone is not alone.", buttonLabel: "JOIN AS VOLUNTEER", href: "/volunteer/register", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165026/moksha-sewa/assets/about-optimized/volunteer.png" },
      { title: "Partner With Us", description: "Join hands to create\na greater and\nlasting impact.", buttonLabel: "EXPLORE PARTNERSHIP", href: "/partnership", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165011/moksha-sewa/assets/about-optimized/partner.png" },
      { title: "Support the Mission", description: "Your support helps ensure\ndignity, care and respect\nin every final journey.", buttonLabel: "SUPPORT THE MISSION", href: "/donation", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165022/moksha-sewa/assets/about-optimized/support.png" },
    ],
  },
  {
    key: "about-faq",
    name: "About FAQ",
    enabled: true,
    eyebrow: "Help & Information",
    title: "Frequently Asked Questions",
    description: "Here are answers to some common questions about Moksha Sewa.\nIf you need more help, we are here for you.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165029/moksha-sewa/assets/about-reference/faq-support-final.png",
    requestTitle: "Need more help?",
    requestDescription: "Our team is here to assist you with any questions or support you may need.",
    buttonLabel: "Request Sewa Help",
    buttonHref: "/contact",
    items: [
      { title: "Who can request Moksha Sewa support?", description: "Moksha Sewa provides support for legally authorised unclaimed bodies, people without family support and verified families facing financial hardship. All requests are subject to verification and eligibility." },
      { title: "Does Moksha Sewa assist with legally authorised unclaimed bodies?", description: "Yes. We coordinate support only after the required authority clearance, documentation and legal formalities have been completed." },
      { title: "What kind of assistance does Moksha Sewa provide?", description: "Depending on verified need and availability, support may include final-journey transport, ritual materials, priest coordination, cremation-ground support and family guidance." },
      { title: "Is Moksha Sewa available in my area?", description: "Moksha Sewa currently focuses on Delhi - Ghaziabad - Noida and is expanding progressively. Contact our team with the case location to confirm availability." },
      { title: "How can I become a volunteer with Moksha Sewa?", description: "Submit the volunteer form through our website. Our team will review your details and contact you when a suitable verified opportunity is available." },
      { title: "How can I support Moksha Sewa through donations?", description: "You can support verified cases through the official donation page. Contributions are used responsibly for eligible mission activities and case-based assistance." },
    ],
  },
  {
    key: "about-heart",
    name: "Heart Of Moksha",
    enabled: true,
    eyebrow: "The Heart of Moksha Sewa",
    title: "When Someone Has No One,\nHumanity Must Stand Beside Them.",
    description: "Because the final journey is not only about how life ends. It is about how we choose to stand beside one another until the very end.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165038/moksha-sewa/assets/about-reference/heart-of-moksha-sewa.png",
    buttonLabel: "Join the Mission",
    buttonHref: "/volunteer/register",
    items: [
      { label: "Be a\nVolunteer" },
      { label: "Partner\nWith Us" },
      { label: "Support the\nMission" },
    ],
  },
  {
    key: "about-hero-slider",
    name: "About Hero Slider",
    enabled: true,
    eyebrow: "Moksha Sewa",
    title: "Every Life Deserves Dignity. Always.",
    subtitle: "A Promise of Moksha Sewa",
    description: "Moksha Sewa stands for compassion in action. We are here for the forgotten, the unclaimed, and those who have no one. Because no one should face their final journey alone.",
    secondaryDescription: "Moksha Sewa is a humanitarian end-of-life support mission for economically weaker families and legally authorised unclaimed cases.",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164987/moksha-sewa/assets/about-optimized/about.webp",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164983/moksha-sewa/assets/about-optimized/about-hero-new.webp",
    logoImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164952/moksha-sewa/hero-images/image6.png",
    buttonLabel: "Request Help",
    buttonHref: "/request-help",
    secondaryButtonLabel: "Support This Mission",
    secondaryButtonHref: "/donation",
    phoneLabel: "24/7 Helpline",
    phoneNumber: "+91 9220147229",
    supportTitle: "Moksha Sewa",
    supportDescription: "An Initiative of Namo Gange Trust",
    items: [
      { title: "Dignity First" },
      { title: "Eligibility-Based" },
      { title: "Always Available" },
    ],
  },
  {
    key: "about-moksha-sewa-story",
    name: "About Moksha Sewa (Our Story Section)",
    enabled: true,
    eyebrow: "Our Story",
    title: "Compassion, Care & Verified Support",
    description: "Moksha Sewa was founded with one simple belief: every final journey deserves dignity. We support economically weaker families and legally authorised unclaimed cases through verified, compassionate coordination.",
    quote: "Serving with Devotion",
    legalNotice: "Team Moksha Sewa",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164984/moksha-sewa/assets/about-optimized/about-story-1.webp",
    secondaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164985/moksha-sewa/assets/about-optimized/about-story-2.webp",
    tertiaryImage: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788164986/moksha-sewa/assets/about-optimized/about-story-3.webp",
  },
  {
    key: "about-board-members",
    name: "Mission Leadership / Board Members",
    enabled: true,
    eyebrow: "Leadership & Governance",
    title: "Mission Leadership",
    items: [
      { title: "Madhukar Reddy Dasari", subtitle: "Namo Gange Trust Leadership", description: "Supports governance, finance and operational oversight for the mission.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165005/moksha-sewa/assets/about-optimized/madhukar-reddy-dasari.webp" },
      { title: "Sandeep Singh", subtitle: "Technology & Data Support", description: "Supports technology, data security and platform infrastructure.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165019/moksha-sewa/assets/about-optimized/sandeep-singh.webp" },
      { title: "Vijay Sharma", subtitle: "Operations Coordination", description: "Supports on-ground coordination, field execution and case response.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165477/moksha-sewa/assets/vijay_sharma.jpg" },
      { title: "Srujana Paid", subtitle: "Partnerships & Outreach", description: "Supports partnerships, outreach and progressive mission expansion.", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165020/moksha-sewa/assets/about-optimized/srujana-paid.webp" },
    ],
  },
  {
    key: "about-founders-vision",
    name: "Founder's Vision",
    enabled: true,
    eyebrow: "Founder's Vision",
    title: "The Thought Behind Moksha Sewa",
    image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165477/moksha-sewa/assets/vijay_sharma.jpg",
    supportTitle: "Vijay Sharma",
    supportDescription: "Founder",
    description: "When a family loses a loved one, they are overwhelmed with grief. At that critical moment, dealing with the logistics of rituals, cremation, and arrangements should not add to their burden. Moksha Sewa was born out of this very realization.",
    secondaryDescription: "Our vision is to provide absolute dignity, complete transparency, and compassionate care to families during their toughest times. Every ritual is guided by deep respect for our traditions, ensuring that the final journey is peaceful and honorable.",
  },
  {
    key: "about-our-initiatives",
    name: "Our Namo Gange Initiatives",
    enabled: true,
    eyebrow: "Our Expanding Horizon",
    title: "Our Namo Gange Initiatives",
    items: [
      { title: "Meri Beti Mera Abhiman", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165232/moksha-sewa/assets/initiatives/meri%20beti%20mera%20abhiman.webp" },
      { title: "Arogya Mantra", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165212/moksha-sewa/assets/initiatives/Arogya%20Mantra.webp" },
      { title: "The Yogshala Expo", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165229/moksha-sewa/assets/initiatives/The%20Yogshala%20Expo.webp" },
      { title: "The Yogshala Jobs", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165230/moksha-sewa/assets/initiatives/The%20Yogshala%20Jobs.webp" },
      { title: "Swachh Bharat Sankalp", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165225/moksha-sewa/assets/initiatives/Swachh%20Bharat%20Sankalp.webp" },
      { title: "Indian Contemporary Art", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165220/moksha-sewa/assets/initiatives/Indian%20Contemporary%20Art.webp" },
      { title: "ICOA", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165219/moksha-sewa/assets/initiatives/ICOA.webp" },
      { title: "Acharaya ji Online", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165209/moksha-sewa/assets/initiatives/Acharaya%20ji%20Online.webp" },
      { title: "Aviral Ganga", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165214/moksha-sewa/assets/initiatives/Aviral%20Ganga.webp" },
      { title: "Arogya Film Festival", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165211/moksha-sewa/assets/initiatives/Arogya%20Film%20Festival.webp" },
      { title: "Indo Himalayan Expo", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165221/moksha-sewa/assets/initiatives/Indo%20Himalayan%20Expo.webp" },
      { title: "Anna Sewa", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165210/moksha-sewa/assets/initiatives/Anna%20Sewa.webp" },
      { title: "NGT Farms", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165223/moksha-sewa/assets/initiatives/NGT%20Farms.webp" },
      { title: "The Grand Master of Yoga", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165226/moksha-sewa/assets/initiatives/The%20Grand%20Master%20of%20Yoga.webp" },
      { title: "Arogya Sangoshti", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165213/moksha-sewa/assets/initiatives/Arogya%20Sangoshti.webp" },
      { title: "Bachchan Ki Rangshala", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165217/moksha-sewa/assets/initiatives/Bachchan%20Ki%20Rangshala.webp" },
      { title: "Ayush Mitra", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165216/moksha-sewa/assets/initiatives/Ayush%20Mitra.webp" },
      { title: "Vaidhyashala", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165231/moksha-sewa/assets/initiatives/Vaidhyashala.webp" },
      { title: "Global Eco-Tech Expo", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165218/moksha-sewa/assets/initiatives/Global%20Eco-Tech%20Expo.webp" },
      { title: "Ayush Abhinandanam", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165215/moksha-sewa/assets/initiatives/Ayush%20Abhinandanam.webp" },
      { title: "MP Development Expo", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165222/moksha-sewa/assets/initiatives/MP%20Development%20Expo.webp" },
      { title: "Shrimad Bhagwat Katha", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165224/moksha-sewa/assets/initiatives/Shrimad%20Bhagwat%20Katha.webp" },
      { title: "The Yogshala Clinic", image: "https://res.cloudinary.com/dr8mld4i0/image/upload/v1788165228/moksha-sewa/assets/initiatives/The%20Yogshala%20Clinic.webp" },
    ],
  },
];

export function mergeAboutSections(sections?: AboutSectionContent[]): AboutSectionContent[] {
  if (!sections?.length) return defaultAboutSections;
  const byKey = new Map(sections.map((section) => [section.key, section]));
  return defaultAboutSections.map((fallback) => {
    const saved = byKey.get(fallback.key);
    if (!saved) return fallback;
    const items = saved.items !== undefined ? saved.items : fallback.items;
    return normalizeLandingSection({ ...fallback, ...saved, items, enabled: saved.enabled !== false }, fallback);
  });
}
