import { normalizeLandingSection, type LandingSectionContent } from "./landingContent";

export type AboutSectionContent = LandingSectionContent;

export const defaultAboutSections: AboutSectionContent[] = [
  {
    key: "about-hero",
    name: "About Hero",
    enabled: true,
    eyebrow: "About Moksha Sewa",
    title: "Serving the Final Journey With Dignity",
    subtitle: "A humanitarian initiative of Namo Gange Trust.",
    description: "Moksha Sewa stands beside families, authorised unclaimed cases and people without support with care, responsibility and compassion.",
    image: "/hero-images/dignity-in-every-final-journey-bg.png",
    logoImage: "/hero-images/image6.png",
    buttonLabel: "Request Sewa Help",
    buttonHref: "/request-help",
    secondaryButtonLabel: "Support This Mission",
    secondaryButtonHref: "/donation",
    quote: "We do not see a case. We see a human life that deserves respect.",
    items: [
      { title: "For Those Unclaimed", description: "Dignified rites for unclaimed." },
      { title: "For Those Alone", description: "Support for the alone." },
      { title: "For Families in Need", description: "Help for families in need." },
      { title: "With Dignity & Care", description: "Compassion in every farewell." },
      { title: "Humanity First", description: "Every life is precious and deserves respect." },
      { title: "Verification & Legal", description: "We follow formalities and check eligibility first." },
      { title: "Transparent Sewa", description: "Accountable and compassionate at every step." },
      { title: "Community Powered", description: "Powered by volunteers, supporters and partners." },
    ],
  },
  {
    key: "about-who-we-are",
    name: "Who We Are",
    enabled: true,
    eyebrow: "Who We Are",
    title: "Moksha Sewa Is a Namo Gange Trust Initiative.",
    description: "Moksha Sewa is a dedicated humanitarian initiative of Namo Gange Trust, created to provide compassionate and responsible support for authorised unclaimed cases, people without family support, and verified families facing financial hardship.",
    secondaryDescription: "The initiative operates under the guidance and institutional framework of Namo Gange Trust, bringing together volunteers, coordinators, service partners and compassionate citizens to support dignified final journeys.",
    image: "/assets/about-reference/who-we-are-background-v2.png",
    logoImage: "/assets/logo-moksha-seva.png",
    bottomStatement: "Together, we ensure that no one is left without dignity, care and respect in their final journey.",
    items: [
      { title: "Compassion", description: "At Every Step" },
      { title: "Integrity", description: "In Every Action" },
      { title: "Respect", description: "For Every Life" },
      { title: "Dignity", description: "In Every Journey" },
    ],
  },
  {
    key: "about-moksha-sewa",
    name: "What Is Moksha Sewa",
    enabled: true,
    eyebrow: "What Is Moksha Sewa?",
    title: "A Mission Built\nAround Dignity.",
    description: "Moksha Sewa is a humanitarian initiative created to stand beside people during one of life's most difficult and sensitive moments - the final journey.",
    secondaryDescription: "It focuses on authorised unclaimed cases, people without available family support, and verified families who may face financial hardship in arranging essential final-journey requirements.",
    image: "/assets/about-optimized/a_mission.png",
  },
  {
    key: "about-services",
    name: "What We Do",
    enabled: true,
    eyebrow: "What We Do",
    title: "Supporting the\nFinal Journey With Care.",
    description: "We provide compassionate and responsible support for every step of the final journey.",
    image: "/assets/about-optimized/moksha_services_bg.png",
    buttonLabel: "Explore Our Sewa",
    buttonHref: "/prayerhallservices",
    secondaryTitle: "How We Serve",
    items: [
      { title: "Final-Journey\nTransport", description: "Dignified and timely transport to the cremation destination.", image: "/assets/about-optimized/final_journey_support.png" },
      { title: "Cremation &\nLast-Rites Support", description: "Complete support for cremation and essential last-rites arrangements.", image: "/assets/about-optimized/cremation.png" },
      { title: "Ritual & Priest\nCoordination", description: "Arranging priests and guidance for all required rituals with respect.", image: "/assets/about-optimized/ritual.png" },
      { title: "Essential\nMaterials", description: "Providing all essential items required for the final rites.", image: "/assets/about-optimized/essentials.png" },
      { title: "Family\nGuidance", description: "Emotional support and guidance for families during difficult times.", image: "/assets/about-optimized/family_guidance.png" },
      { value: "01", title: "Understand", description: "We listen to the circumstances.", image: "/assets/about-optimized/understand.png" },
      { value: "02", title: "Verify", description: "Eligibility and required formalities are reviewed.", image: "/assets/about-optimized/verify.png" },
      { value: "03", title: "Coordinate", description: "Essential support is arranged as applicable.", image: "/assets/about-optimized/coordinate.png" },
      { value: "04", title: "Stand Beside", description: "Compassionate on-ground guidance continues through the process.", image: "/assets/about-optimized/stand_behind.png" },
    ],
  },
  {
    key: "about-how-support",
    name: "Who We Support",
    enabled: true,
    title: "Who We Support",
    legalNotice: "Important Note",
    bottomStatement: "Support is case-based and subject to applicable verification, eligibility, required formalities and available resources.",
    items: [
      { value: "01", title: "Unclaimed &\nAuthorised Cases", description: "Support for authorised cases after applicable procedures, permissions and formalities.", image: "/assets/about-reference/story-ghat-temple.png" },
      { value: "02", title: "People Without\nFamily Support", description: "Compassionate assistance for people who have no family or support system available to stand beside them.", image: "/assets/about-reference/story-evening-ghat.png" },
      { value: "03", title: "Verified Families Facing\nFinancial Hardship", description: "Case-based assistance for families who need help with essential final-rites arrangements.", image: "/assets/about-optimized/family-support.webp" },
    ],
  },
  {
    key: "about-why-exist",
    name: "Why We Exist",
    enabled: true,
    eyebrow: "Why We Exist",
    title: "Because Sometimes,\nThere Is No One Left\nto Stand Beside Them.",
    subtitle: "Moksha Sewa\nExists for These Moments.",
    description: "Some people leave this world without family or support.\nSome cases remain unclaimed. And some families have the love and willingness to perform the final rites, but do not have the financial means to manage everything on their own.",
    quote: "When support disappears,\nhumanity must step forward.",
    image: "/assets/about-optimized/existimage.png",
  },
  {
    key: "about-behind-mission",
    name: "Mission Video",
    enabled: true,
    eyebrow: "Video",
    title: "Behind\nMoksha Sewa",
    subtitle: "See the Mission",
    description: "Every final journey carries a story. This is the story of a mission built around responsibility, compassion and the belief that no one should be left without dignity.",
    image: "/vedio/taniya.mp4",
    secondaryImage: "/hero-images/support-mission-ghat.png",
    availabilityText: "60-90 seconds",
    buttonLabel: "Explore Our Work",
    buttonHref: "/mokshagallery",
    items: [
      { title: "WHAT", label: "We Do" },
      { title: "WHY", label: "We Exist" },
      { title: "WHO", label: "We Serve" },
      { title: "HOW", label: "We Serve" },
      { title: "NAMO GANGE TRUST", label: "Our Foundation" },
    ],
  },
  {
    key: "about-our-story",
    name: "Our Story & Founder Message",
    enabled: true,
    eyebrow: "Our Story",
    title: "One Question\nBecame a Mission.",
    subtitle: "What happens when someone passes away\nand there is no one to stand beside them?",
    description: "This question became the foundation of Moksha Sewa—a mission created so that when someone is left without family, support or resources, humanity can still stand beside them.\n\nWe believe that every individual, regardless of identity, status or circumstance, deserves a final journey of dignity, respect and compassion.",
    quote: "Dignity should never depend on whether someone has money, family or someone standing beside them.",
    secondaryTitle: "A Message From The Founder",
    secondaryDescription: "Moksha Sewa is not just a service—it is a promise. A promise that in someone's final moment, humanity will not look away.",
    image: "/assets/vijay_sharma.jpg",
  },
  {
    key: "about-namo-gange",
    name: "Namo Gange Trust",
    enabled: true,
    eyebrow: "The Organisation Behind Moksha Sewa",
    title: "Rooted in Service.\nDriven by Responsibility.",
    description: "Moksha Sewa is an initiative of Namo Gange Trust, an organisation committed to social service, community welfare and meaningful humanitarian action.",
    secondaryDescription: "Through Moksha Sewa, Namo Gange Trust extends this commitment to one of the most sensitive moments of human life - the final journey.",
    image: "/assets/videos/namoGange.mp4",
    buttonLabel: "Know Namo Gange Trust",
    buttonHref: "https://www.namogange.org/",
    items: [
      { label: "Social Service" },
      { label: "Community Welfare" },
      { label: "Humanitarian Action" },
      { label: "Responsible Governance" },
    ],
  },
  {
    key: "about-responsible-sewa",
    name: "Responsible Sewa",
    enabled: true,
    eyebrow: "Responsible Sewa",
    title: "Compassion\nWith Accountability.",
    subtitle: "We serve with responsibility. Because dignity comes first.",
    description: "At Moksha Sewa, every act of support is guided by responsibility, respect and the highest standards of ethical service.\n\nWe ensure that no one is left behind, working with deep empathy to provide dignity when it is needed most.",
    bottomStatement: "Moksha Sewa is a Namo Gange Trust initiative. Every step we take is guided by responsibility, respect and humanity.",
    image: "/assets/about/our-story/response.jpeg",
    items: [
      { title: "Verification", description: "Support follows defined eligibility and case circumstances." },
      { title: "Formalities", description: "Applicable permissions and procedures are respected." },
      { title: "Documentation", description: "Cases and assistance are responsibly recorded." },
      { title: "Privacy", description: "Beneficiary dignity comes before publicity." },
    ],
  },
  {
    key: "about-support-mission",
    name: "Support The Mission",
    enabled: true,
    eyebrow: "Support The Mission",
    title: "Help Namo Gange Trust\nContinue Moksha Sewa.",
    description: "Moksha Sewa is a humanitarian initiative of Namo Gange Trust. Your contribution helps support the Trust's efforts to provide dignified and responsible final-journey assistance through the Moksha Sewa initiative.",
    image: "/assets/about/our-story/arthi.jpeg",
    legalNotice: "Contributions made through this website are received by Namo Gange Trust and are utilised towards eligible activities and support under the Moksha Sewa initiative, subject to applicable policies and requirements.",
    items: [
      { title: "Essential final-journey arrangements" },
      { title: "Transportation & coordination" },
      { title: "Ritual requirements" },
      { title: "Eligible family support" },
      { title: "On-ground coordination" },
      { title: "Secure & Trusted", description: "Safe donations through trusted gateway" },
      { title: "Accountable Use", description: "Funds used for eligible activities only" },
      { title: "Transparency First", description: "Committed to responsible reporting" },
      { title: "Sewa With Dignity", description: "Ensuring respect and compassion in every step of the final journey" },
    ],
  },
  {
    key: "about-join-sewa",
    name: "Be Part Of The Sewa",
    enabled: true,
    eyebrow: "BE PART OF THE SEWA",
    title: "You Don't Have to\nDo Everything.",
    subtitle: "You Can Simply Do Something.",
    description: "Every act of kindness creates a ripple of dignity, compassion and respect. Even a small contribution of time, care or support can bring comfort to someone during their most difficult moments and help ensure that no one has to face their final journey alone.\n\nWhether you give your time as a volunteer, partner with us as an organisation, or support a family directly, every contribution helps us stand beside those who need it most — with dignity, care and respect.",
    bottomStatement: "Together, we can make sure that no one has to face their final journey alone. Be Part of the Sewa. Be the change.",
    image: "/assets/about-optimized/be_part.png",
    items: [
      { title: "Become a Volunteer", description: "Give your time.\nBring compassion.\nBe the reason someone is not alone.", buttonLabel: "JOIN AS VOLUNTEER", href: "/volunteer/register", image: "/assets/about-optimized/volunteer.png" },
      { title: "Partner With Us", description: "Join hands to create\na greater and\nlasting impact.", buttonLabel: "EXPLORE PARTNERSHIP", href: "/partnership", image: "/assets/about-optimized/partner.png" },
      { title: "Support the Mission", description: "Your support helps ensure\ndignity, care and respect\nin every final journey.", buttonLabel: "SUPPORT THE MISSION", href: "/donation", image: "/assets/about-optimized/support.png" },
    ],
  },
  {
    key: "about-faq",
    name: "About FAQ",
    enabled: true,
    eyebrow: "Help & Information",
    title: "Frequently Asked Questions",
    description: "Here are answers to some common questions about Moksha Sewa.\nIf you need more help, we are here for you.",
    image: "/assets/about-reference/faq-support-final.png",
    requestTitle: "Need more help?",
    requestDescription: "Our team is here to assist you with any questions or support you may need.",
    buttonLabel: "Request Sewa Help",
    buttonHref: "/contact",
    items: [
      { title: "Who can request Moksha Sewa support?", description: "Moksha Sewa provides support for legally authorised unclaimed bodies, people without family support and verified families facing financial hardship. All requests are subject to verification and eligibility." },
      { title: "Does Moksha Sewa assist with legally authorised unclaimed bodies?", description: "Yes. We coordinate support only after the required authority clearance, documentation and legal formalities have been completed." },
      { title: "What kind of assistance does Moksha Sewa provide?", description: "Depending on verified need and availability, support may include final-journey transport, ritual materials, priest coordination, cremation-ground support and family guidance." },
      { title: "Is Moksha Sewa available in my area?", description: "Moksha Sewa currently focuses on Delhi - Ghaziabad - Noida and is expanding progressively. Contact our team with the case location to confirm availability." },
      { title: "How can I become a volunteer with Moksha Sewa?", description: "Submit the volunteer form through our website. Our team will review your details and contact you when a suitable verified opportunity is available." },
      { title: "How can I support Moksha Sewa through donations?", description: "You can support verified cases through the official donation page. Contributions are used responsibly for eligible mission activities and case-based assistance." },
    ],
  },
  {
    key: "about-heart",
    name: "Heart Of Moksha",
    enabled: true,
    eyebrow: "The Heart of Moksha Sewa",
    title: "When Someone Has No One,\nHumanity Must Stand Beside Them.",
    description: "Because the final journey is not only about how life ends. It is about how we choose to stand beside one another until the very end.",
    image: "/assets/about-reference/heart-of-moksha-sewa.png",
    buttonLabel: "Join the Mission",
    buttonHref: "/volunteer/register",
    items: [
      { label: "Be a\nVolunteer" },
      { label: "Partner\nWith Us" },
      { label: "Support the\nMission" },
    ],
  },
];

export function mergeAboutSections(sections?: AboutSectionContent[]): AboutSectionContent[] {
  if (!sections?.length) return defaultAboutSections;
  const byKey = new Map(sections.map((section) => [section.key, section]));
  return defaultAboutSections.map((fallback) => {
    const saved = byKey.get(fallback.key);
    if (!saved) return fallback;
    const items = saved.items !== undefined ? saved.items : fallback.items;
    return normalizeLandingSection({ ...fallback, ...saved, items, enabled: saved.enabled !== false }, fallback);
  });
}
